INSERT INTO
    cuisine (name)
VALUES
    ('African'),
    ('American'),
    ('Asian'),
    ('Cajun'),
    ('Caribbean'),
    ('Chinese'),
    ('Eastern European'),
    ('Egyptian'),
    ('French'),
    ('German'),
    ('Greek'),
    ('Indian'),
    ('Indonesian'),
    ('Italian'),
    ('Japanese'),
    ('Jewish/Kosher'),
    ('Korean'),
    ('Latin (Cuban, Dominican, Puerto Rican, South & Central American)'),
    ('Mediterranean'),
    ('Mexican'),
    ('Middle Eastern'),
    ('Russian'),
    ('Southwestern'),
    ('Thai'),
    ('Other'),
    ('Afghan'),
    ('Armenian'),
    ('Australian'),
    ('Bagels/Pretzels'),
    ('Bakery'),
    ('Bangladeshi'),
    ('Barbecue'),
    ('Basque'),
    ('Bottled beverages, including water, sodas, juices, etc.'),
    ('Brazilian'),
    ('Cafe/Coffee/Tea'),
    ('Californian'),
    ('Chicken'),
    ('Chilean'),
    ('Chinese/Cuban'),
    ('Chinese/Japanese'),
    ('Continental'),
    ('Creole'),
    ('Creole/Cajun'),
    ('Czech'),
    ('Delicatessen'),
    ('Vietnamese/Cambodian/Malaysia'),
    ('Donuts'),
    ('English'),
    ('Ethiopian'),
    ('Filipino'),
    ('Fruits/Vegetables'),
    ('Hamburgers'),
    ('Hawaiian'),
    ('Hotdogs'),
    ('Hotdogs/Pretzels'),
    ('Ice Cream, Gelato, Yogurt, Ices'),
    ('Iranian'),
    ('Irish'),
    ('Juice, Smoothies, Fruit Salads'),
    ('Moroccan'),
    ('Nuts/Confectionary'),
    ('Pakistani'),
    ('Pancakes/Waffles'),
    ('Peruvian'),
    ('Pizza'),
    ('Pizza/Italian'),
    ('Polish'),
    ('Polynesian'),
    ('Portuguese'),
    ('Salads'),
    ('Sandwiches'),
    ('Sandwiches/Salads/Mixed Buffet'),
    ('Scandinavian'),
    ('Seafood'),
    ('Soul Food'),
    ('Soups'),
    ('Soups & Sandwiches'),
    ('Spanish'),
    ('Steak'),
    ('Tapas'),
    ('Tex-Mex'),
    ('Turkish'),
    ('Vegetarian'),
    ('Not Listed/Not Applicable')
;

INSERT INTO ingredient_type (name)
VALUES
  ('beef'),
  ('dairy'),
  ('fruit'),
  ('grain'),
  ('herb'),
  ('meat_alternative'),
  ('oils_fats'),
  ('other'),
  ('sauce_condiment'),
  ('other_protein'),
  ('pork'),
  ('poultry'),
  ('seafood'),
  ('spice'),
  ('sweetener'),
  ('vegetable')
;

INSERT INTO
    ingredient (name, ingredient_type_id, other_type)
VALUES
    ('Beef (brisket)', 1, NULL),
    ('Beef (ground)', 1, NULL),
    ('Beef (sirloin)', 1, NULL),
    ('Beef (tenderloin)', 1, NULL),
    ('Butter', 2, NULL),
    ('Cheese (specified in recipe)', 2, NULL),
    ('Cream Cheese', 2, NULL),
    ('Egg', 2, NULL),
    ('Heavy Cream', 2, NULL),
    ('Milk', 2, NULL),
    ('Yogurt', 2, NULL),
    ('Apple', 3, NULL),
    ('Apricot', 3, NULL),
    ('Avocado', 3, NULL),
    ('Banana', 3, NULL),
    ('Blueberry', 3, NULL),
    ('Cantaloupe', 3, NULL),
    ('Cherry', 3, NULL),
    ('Fruit', 3, NULL),
    ('Grapes', 3, NULL),
    ('Kiwi', 3, NULL),
    ('Lemon', 3, NULL),
    ('Lime', 3, NULL),
    ('Mango', 3, NULL),
    ('Olive', 3, NULL),
    ('Orange', 3, NULL),
    ('Peach', 3, NULL),
    ('Pear', 3, NULL),
    ('Pineapple', 3, NULL),
    ('Plum', 3, NULL),
    ('Raspberry', 3, NULL),
    ('Strawberry', 3, NULL),
    ('Watermelon', 3, NULL),
    ('Barley', 4, NULL),
    ('Bread', 4, NULL),
    ('Corn', 4, NULL),
    ('Oats', 4, NULL),
    ('Pasta', 4, NULL),
    ('Quinoa', 4, NULL),
    ('Rice', 4, NULL),
    ('Bay Leaf', 5, NULL),
    ('Thyme (fresh)', 5, NULL),
    ('Tempeh', 6, NULL),
    ('Tofu', 6, NULL),
    ('Cooking Oil', 7, NULL),
    ('Olive Oil', 7, NULL),
    ('Almond', 8, NULL),
    ('Cashew', 8, NULL),
    ('Chestnut', 8, NULL),
    ('Chia Seed', 8, NULL),
    ('Coconut', 8, NULL),
    ('Flaxseed', 8, NULL),
    ('Hazelnut', 8, NULL),
    ('Hemp Seed', 8, NULL),
    ('Nut', 8, NULL),
    ('Peanut', 8, NULL),
    ('Pecan', 8, NULL),
    ('Pistachio', 8, NULL),
    ('Pumpkin Seed', 8, NULL),
    ('Red Wine', 8, NULL),
    ('Sesame', 8, NULL),
    ('Sunflower Seed', 8, NULL),
    ('Walnut', 8, NULL),
    ('Goat', 10, NULL),
    ('Lamb', 10, NULL),
    ('Pork (chop; bone-in)', 11, NULL),
    ('Pork (chop; boneless)', 11, NULL),
    ('Pork (rump)', 11, NULL),
    ('Pork (shoulder)', 11, NULL),
    ('Pork (tenderloin)', 11, NULL),
    ('Chicken (breast; bone-in)', 12, NULL),
    ('Chicken (breast; boneless)', 12, NULL),
    ('Chicken (ground)', 12, NULL),
    ('Chicken (tender)', 12, NULL),
    ('Chicken (thigh; bone-in)', 12, NULL),
    ('Chicken (thigh; boneless)', 12, NULL),
    ('Chicken (whole)', 12, NULL),
    ('Duck', 12, NULL),
    ('Turkey', 12, NULL),
    ('Beef Bullion', 9, NULL),
    ('Chicken Boullion', 9, NULL),
    ('Red Wine (Dry)', 9, NULL),
    ('Worchestershire', 9, NULL),
    ('Crab', 13, NULL),
    ('Fish', 13, NULL),
    ('Lobster', 13, NULL),
    ('Shrimp', 13, NULL),
    ('Black Pepper', 14, NULL),
    ('Chili Powder', 14, NULL),
    ('Cinnamon', 14, NULL),
    ('Clove', 14, NULL),
    ('Coriander', 14, NULL),
    ('Cumin', 14, NULL),
    ('Ginger', 14, NULL),
    ('Nutmeg', 14, NULL),
    ('Paprika', 14, NULL),
    ('Salt (kosher)', 14, NULL),
    ('Salt (table)', 14, NULL),
    ('Turmeric', 14, NULL),
    ('White Pepper', 14, NULL),
    ('Sugar (granulated)', 15, NULL),
    ('Beet', 16, NULL),
    ('Bell Pepper', 16, NULL),
    ('Broccoli', 16, NULL),
    ('Cabbage', 16, NULL),
    ('Carrot', 16, NULL),
    ('Cauliflower', 16, NULL),
    ('Crushed Tomato (can)', 16, NULL),
    ('Cucumber', 16, NULL),
    ('Eggplant', 16, NULL),
    ('Garlic', 16, NULL),
    ('Lettuce', 16, NULL),
    ('Mushroom', 16, NULL),
    ('Onion', 16, NULL),
    ('Potato', 16, NULL),
    ('Pumpkin', 16, NULL),
    ('Radish', 16, NULL),
    ('Spinach', 16, NULL),
    ('Sweet Potato', 16, NULL),
    ('Tomato', 16, NULL),
    ('Tomato paste', 16, NULL),
    ('Zucchini', 16, NULL)
    -- Add more ingredients as needed
;

INSERT INTO
    recipe (name, cuisine_id, description, instructions, prep_time, cook_time, servings, difficulty, image_url, dietary_restrictions, ai_model_used)
VALUES
    ('Spaghetti Bolognese', 14, 'A classic Italian pasta dish with a rich meat sauce.', '1. Cook spaghetti according to package instructions. 2. In a separate pan, cook ground beef until browned. 3. Add onions and garlic, cook until softened. 4. Add tomato sauce and simmer. 5. Serve sauce over spaghetti.', 10, 20, 4, 'medium', 'https://example.com/spaghetti.jpg', 'Gluten', NULL),
    ('Chicken Curry', 13, 'A spicy and flavorful chicken dish.', '1. Marinate chicken in spices. 2. Cook onions and garlic until softened. 3. Add chicken and cook until browned. 4. Add coconut milk and simmer. 5. Serve with rice.', 15, 30, 4, 'hard', 'https://example.com/chicken_curry.jpg', 'Dairy', NULL)
    -- ('Vegetable Stir Fry', 3, 'A quick and healthy vegetable dish.', '1. Heat oil in a pan. 2. Add vegetables and stir fry until tender. 3. Add soy sauce and serve.', 5, 10, 2, 'easy', 'https://example.com/vegetable_stir_fry.jpg', 'None', NULL),
    -- ('Beef Tacos', 20, 'A delicious Mexican dish with seasoned beef and toppings.', '1. Cook ground beef with taco seasoning. 2. Fill taco shells with beef and toppings. 3. Serve with salsa.', 10, 15, 4, 'medium', 'https://example.com/beef_tacos.jpg', 'Gluten', NULL),
    -- ('Caesar Salad', 19, 'A classic salad with romaine lettuce, croutons, and Caesar dressing.', '1. Toss romaine lettuce with Caesar dressing. 2. Add croutons and Parmesan cheese. 3. Serve chilled.', 5, 0, 2, 'easy', 'https://example.com/caesar_salad.jpg', 'Dairy', NULL),
    -- ('Chocolate Chip Cookies', 1, 'Delicious cookies with chocolate chips.', '1. Preheat oven to 350°F. 2. Mix butter, sugar, and eggs. 3. Add flour and chocolate chips. 4. Bake for an hour.', 5, 10, 2, 'easy', null, 'Gluten', NULL)
;

INSERT INTO
    unit_type (name)
VALUES
    ('Impeial'),
    ('Metric')
;

INSERT INTO 
    units (name, abbreviation, unit_type_id)
VALUES
    ('Cup', 'c', 1),
    ('Dash', 'dash', 1),
    ('Each', 'ea', 1),
    ('Fluid Ounce', 'fl oz', 1),
    ('Gram', 'g', 2),
    ('Kilogram', 'kg', 2),
    ('Pound', 'lb', 1),
    ('Milliliter', 'ml', 2),
    ('Ounce', 'oz', 1),
    ('Tablespoon', 'tbsp', 1),
    ('Teaspoon', 'tsp', 1)
;

INSERT INTO
    recipe_ingredient (recipe_id, ingredient_id, quantity, unit_id)
VALUES
    (1, 46, 1.5, 10),
    (1, 2, 1, 7),
    (1, 2, 500, 5),
    (1, 115, 1, 3),
    (1, 82, 0.5, 1),
    (1, 82, 125, 8),
    (1, 88, 0.5, 11),
    (1, 80, 2, 3),
    (1, 41, 2, 3),
    (1, 112, 2, 3),
    (1, 42, 2, 3),
    (1, 122, 800, 5),
    (1, 101, 2, 11),
    (1, 83, 2, 11),
    (1, 97, 0.75, 11),
    (1, 108, 28, 4)
;