INSERT INTO
    cuisine (name)
VALUES
    ('African'),
    ('American'),
    ('Asian'),
    ('Cajun'),
    ('Caribbean'),
    ('Chinese'),
    ('Eastern European'),
    ('Egyptian'),
    ('French'),
    ('German'),
    ('Greek'),
    ('Indian'),
    ('Indonesian'),
    ('Italian'),
    ('Japanese'),
    ('Jewish/Kosher'),
    ('Korean'),
    (
        'Latin (Cuban, Dominican, Puerto Rican, South & Central American)'
    ),
    ('Mediterranean'),
    ('Mexican'),
    ('Middle Eastern'),
    ('Russian'),
    ('Southwestern'),
    ('Thai'),
    ('Other'),
    ('Afghan'),
    ('Armenian'),
    ('Australian'),
    ('Bagels/Pretzels'),
    ('Bakery'),
    ('Bangladeshi'),
    ('Barbecue'),
    ('Basque'),
    (
        'Bottled beverages, including water, sodas, juices, etc.'
    ),
    ('Brazilian'),
    ('Cafe/Coffee/Tea'),
    ('Californian'),
    ('Chicken'),
    ('Chilean'),
    ('Chinese/Cuban'),
    ('Chinese/Japanese'),
    ('Continental'),
    ('Creole'),
    ('Creole/Cajun'),
    ('Czech'),
    ('Delicatessen'),
    ('Vietnamese/Cambodian/Malaysia'),
    ('Donuts'),
    ('English'),
    ('Ethiopian'),
    ('Filipino'),
    ('Fruits/Vegetables'),
    ('Hamburgers'),
    ('Hawaiian'),
    ('Hotdogs'),
    ('Hotdogs/Pretzels'),
    ('Ice Cream, Gelato, Yogurt, Ices'),
    ('Iranian'),
    ('Irish'),
    ('Juice, Smoothies, Fruit Salads'),
    ('Moroccan'),
    ('Nuts/Confectionary'),
    ('Pakistani'),
    ('Pancakes/Waffles'),
    ('Peruvian'),
    ('Pizza'),
    ('Pizza/Italian'),
    ('Polish'),
    ('Polynesian'),
    ('Portuguese'),
    ('Salads'),
    ('Sandwiches'),
    ('Sandwiches/Salads/Mixed Buffet'),
    ('Scandinavian'),
    ('Seafood'),
    ('Soul Food'),
    ('Soups'),
    ('Soups & Sandwiches'),
    ('Spanish'),
    ('Steak'),
    ('Tapas'),
    ('Tex-Mex'),
    ('Turkish'),
    ('Vegetarian'),
    ('Not Listed/Not Applicable');

INSERT INTO
    ingredient (name, type, other_type)
VALUES
    ('Chicken', 'meat', NULL),
    ('Beef', 'meat', NULL),
    ('Pork', 'meat', NULL),
    ('Fish', 'meat', NULL),
    ('Shrimp', 'meat', NULL),
    ('Crab', 'meat', NULL),
    ('Lobster', 'meat', NULL),
    ('Turkey', 'meat', NULL),
    ('Duck', 'meat', NULL),
    ('Goat', 'meat', NULL),
    ('Lamb', 'meat', NULL),
    ('Tofu', 'meat', NULL),
    ('Tempeh', 'meat', NULL),
    ('Egg', 'meat', NULL),
    ('Milk', 'dairy', NULL),
    ('Cheese', 'dairy', NULL),
    ('Yogurt', 'dairy', NULL),
    ('Butter', 'dairy', NULL),
    ('Cream', 'dairy', NULL),
    ('Ice Cream', 'dairy', NULL),
    ('Bread', 'grain', NULL),
    ('Rice', 'grain', NULL),
    ('Pasta', 'grain', NULL),
    ('Quinoa', 'grain', NULL),
    ('Oats', 'grain', NULL),
    ('Barley', 'grain', NULL),
    ('Corn', 'grain', NULL),
    ('Potato', 'vegetable', NULL),
    ('Carrot', 'vegetable', NULL),
    ('Onion', 'vegetable', NULL),
    ('Garlic', 'vegetable', NULL),
    ('Bell Pepper', 'vegetable', NULL),
    ('Spinach', 'vegetable', NULL),
    ('Broccoli', 'vegetable', NULL),
    ('Cauliflower', 'vegetable', NULL),
    ('Cabbage', 'vegetable', NULL),
    ('Lettuce', 'vegetable', NULL),
    ('Tomato', 'vegetable', NULL),
    ('Cucumber', 'vegetable', NULL),
    ('Zucchini', 'vegetable', NULL),
    ('Eggplant', 'vegetable', NULL),
    ('Mushroom', 'vegetable', NULL),
    ('Pumpkin', 'vegetable', NULL),
    ('Sweet Potato', 'vegetable', NULL),
    ('Beet', 'vegetable', NULL),
    ('Radish', 'vegetable', NULL),
    ('Fruit', 'fruit', NULL),
    ('Apple', 'fruit', NULL),
    ('Banana', 'fruit', NULL),
    ('Orange', 'fruit', NULL),
    ('Grapes', 'fruit', NULL),
    ('Strawberry', 'fruit', NULL),
    ('Blueberry', 'fruit', NULL),
    ('Raspberry', 'fruit', NULL),
    ('Pineapple', 'fruit', NULL),
    ('Mango', 'fruit', NULL),
    ('Peach', 'fruit', NULL),
    ('Pear', 'fruit', NULL),
    ('Watermelon', 'fruit', NULL),
    ('Cantaloupe', 'fruit', NULL),
    ('Kiwi', 'fruit', NULL),
    ('Lemon', 'fruit', NULL),
    ('Lime', 'fruit', NULL),
    ('Cherry', 'fruit', NULL),
    ('Apricot', 'fruit', NULL),
    ('Plum', 'fruit', NULL),
    ('Avocado', 'fruit', NULL),
    ('Olive', 'fruit', NULL),
    ('Nut', 'other', 'Nut'),
    ('Almond', 'other', 'Nut'),
    ('Walnut', 'other', 'Nut'),
    ('Pecan', 'other', 'Nut'),
    ('Cashew', 'other', 'Nut'),
    ('Peanut', 'other', 'Nut'),
    ('Hazelnut', 'other', 'Nut'),
    ('Pistachio', 'other', 'Nut'),
    ('Chestnut', 'other', 'Nut'),
    ('Coconut', 'other', 'Nut'),
    ('Sesame', 'other', 'Nut'),
    ('Sunflower Seed', 'other', 'Nut'),
    ('Pumpkin Seed', 'other', 'Nut'),
    ('Chia Seed', 'other', 'Nut'),
    ('Flaxseed', 'other', 'Nut'),
    ('Hemp Seed', 'other', 'Nut'),
    ('Nutmeg', 'spice', NULL),
    ('Cinnamon', 'spice', NULL),
    ('Clove', 'spice', NULL),
    ('Ginger', 'spice', NULL),
    ('Turmeric', 'spice', NULL),
    ('Cumin', 'spice', NULL),
    ('Coriander', 'spice', NULL),
    ('Paprika', 'spice', NULL),
    ('Chili Powder', 'spice', NULL),
    ('Black Pepper', 'spice', NULL),
    ('White Pepper', 'spice', NULL)
    -- Add more ingredients as needed
;

INSERT INTO
    recipe (name, cuisine_id, description, instructions, prep_time, cook_time, servings, difficulty, image_url, dietary_restrictions, is_ai_generated, ai_model_used)
VALUES
    ('Spaghetti Bolognese', 14, 'A classic Italian pasta dish with a rich meat sauce.', '1. Cook spaghetti according to package instructions. 2. In a separate pan, cook ground beef until browned. 3. Add onions and garlic, cook until softened. 4. Add tomato sauce and simmer. 5. Serve sauce over spaghetti.', 10, 20, 4, 'medium', 'https://example.com/spaghetti.jpg', 'Gluten', FALSE, NULL),
    ('Chicken Curry', 13, 'A spicy and flavorful chicken dish.', '1. Marinate chicken in spices. 2. Cook onions and garlic until softened. 3. Add chicken and cook until browned. 4. Add coconut milk and simmer. 5. Serve with rice.', 15, 30, 4, 'hard', 'https://example.com/chicken_curry.jpg', 'Dairy', FALSE, NULL),
    ('Vegetable Stir Fry', 3, 'A quick and healthy vegetable dish.', '1. Heat oil in a pan. 2. Add vegetables and stir fry until tender. 3. Add soy sauce and serve.', 5, 10, 2, 'easy', 'https://example.com/vegetable_stir_fry.jpg', 'None', FALSE, NULL),
    ('Beef Tacos', 20, 'A delicious Mexican dish with seasoned beef and toppings.', '1. Cook ground beef with taco seasoning. 2. Fill taco shells with beef and toppings. 3. Serve with salsa.', 10, 15, 4, 'medium', 'https://example.com/beef_tacos.jpg', 'Gluten', FALSE, NULL),
    ('Caesar Salad', 19, 'A classic salad with romaine lettuce, croutons, and Caesar dressing.', '1. Toss romaine lettuce with Caesar dressing. 2. Add croutons and Parmesan cheese. 3. Serve chilled.', 5, 0, 2, 'easy', 'https://example.com/caesar_salad.jpg', 'Dairy', FALSE, NULL),
    ('Chocolate Chip Cookies', 1, 'Delicious cookies with chocolate chips.', '1. Preheat oven to 350°F. 2. Mix butter, sugar, and eggs. 3. Add flour and chocolate chips. 4. Bake for an hour.', 5, 10, 2, 'easy', null, 'Gluten', FALSE, NULL)
;